TEXT = " "
TEXT_AUTOSPIN  = "AUTO\nSPIN";
TEXT_WIN       = "WIN";
TEXT_OK        = "OK";
TEXT_STOP_AUTO = "STOP\nAUTO";
TEXT_CURRENCY  = "$";
TEXT_BONUS_HELP = "SPIN THE WHEEL!!";

TEXT_NO_MAX_BET = "NOT ENOUGH MONEY FOR MAX BET!!";
TEXT_CONNECTION_LOST = "CONNECTION DOWN! PLEASE TRY AGAIN";
TEXT_NOT_ENOUGH_MONEY = "NOT ENOUGH MONEY FOR THE CURRENT BET!";

TEXT_CONGRATULATIONS = "Congratulations!";
TEXT_MSG_SHARE1 = "You collected <strong>";
TEXT_MSG_SHARE2= " points</strong>!<br><br>Share your score with your friends!";
TEXT_MSG_SHARING1 = "My score is ";
TEXT_MSG_SHARING2 = " points! Can you do better?";
